#!/bin/sh

uci show cjdns | grep ipv6 >/dev/null 2>&1
if [ $? -ne 0 ]; then

  # generate configuration
  touch /etc/config/cjdns
  cjdroute --genconf | cjdroute --cleanconf | cjdrouteconf set
  uci commit cjdns

fi

exit 0
