#!/bin/sh /etc/rc.common

START=90
STOP=85

USE_PROCD=1

start_service()
{
	[ -f /etc/uci-defaults/cjdns ] && ( . /etc/uci-defaults/cjdns )

	procd_open_instance
	procd_set_param respawn
	procd_set_param command /bin/ash -c "cjdrouteconf get | cjdroute"
	procd_close_instance
}

stop_service()
{
	killall cjdroute
}

service_triggers()
{
	procd_add_reload_trigger "cjdns"
}
