#!/bin/sh /etc/rc.common

START=90
STOP=85

USE_PROCD=1

start_service()
{
	[ -f /etc/uci-defaults/cjdns ] && ( . /etc/uci-defaults/cjdns )

	procd_open_instance
	procd_set_param respawn
	procd_set_param command /bin/ash -c "cjdrouteconf get | cjdroute"
	procd_close_instance

	procd_open_instance
	procd_set_param respawn
	procd_set_param command cjdrouteconf manage
	procd_close_instance
}

stop_service()
{
	procd_kill cjdns
	# FIXME: procd_kill only kills the shell, and cjdroute itself stays open :/
	killall cjdroute || true
}

reload_service()
{
	ubus call cjdns2 reload
}

service_triggers()
{
	procd_add_reload_trigger cjdns
}
